version: "3.8"

services:
  inventory:
    depends_on:
      broker:
        condition: service_healthy
    build:
      context: inventory
      args:
        NODEJS_DOCKER_IMAGE: ${NODEJS_DOCKER_IMAGE}
    restart: always
    volumes:
      - ./inventory:/app
      - /app/node_modules
    ports:
      - 3002:3000
    command: [yarn, start:debug]
    networks:
      - app-network

  payment:
    depends_on:
      broker:
        condition: service_healthy
    build:
      context: payment
      args:
        NODEJS_DOCKER_IMAGE: ${NODEJS_DOCKER_IMAGE}
    restart: always
    volumes:
      - ./payment:/app
      - /app/node_modules
    ports:
      - 3001:3000
    command: [yarn, start:debug]
    networks:
      - app-network

  order:
    depends_on:
      broker:
        condition: service_healthy
      payment:
        condition: service_started
      inventory:
        condition: service_started
    restart: always
    build:
      context: order
      args:
        NODEJS_DOCKER_IMAGE: ${NODEJS_DOCKER_IMAGE}
    volumes:
      - ./order:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: [yarn, start:debug]
    networks:
      - app-network
      
  broker:
    image: bitnami/kafka:3.3.1
    volumes:
      - kafka_data:/var/lib/kafka/data
    user: root
    ports:
      - 9092:9092
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://broker:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=LelM2dIFQkiUFvXCEcqRWA
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@broker:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 10s
      retries: 5
volumes:
  kafka_data:

networks: 
  app-network:
    driver: bridge
