export enum MessagePatternEnum {
  HELLO_WORLD = 'HELLO_WORLD',
  CHECK_PRODUCT_AVAILABILITY = 'CHECK_PRODUCT_AVAILABILITY',
  RESTOCK_QUANTITY = 'RESTOCK_QUANTITY',
  REDUCE_STOCK_QUANTITY = 'REDUCE_STOCK_QUANTITY',
  PAYMENT_AUTHORIZE = 'PAYMENT_AUTHORIZE',
  PAYMENT_REFUND = 'PAYMENT_REFUND',
}
