export enum MessagePatternEnum {
  HELLO_WORLD = 'HELLO_WORLD',
  CHECK_PRODUCT_AVAILABILITY = 'CHECK_PRODUCT_AVAILABILITY',
  RESTOCK_QUANTITY = 'RESTOCK_QUANTITY',
  REDUCE_STOCK_QUANTITY = 'REDUCE_STOCK_QUANTITY',
}
